#! /bin/sh
set -e


# $1=original $2=diverted
undivert()
{
	old_diverter="$(dpkg-divert --listpackage "$1")"
	test -z "$old_diverter" || \
		dpkg-divert --remove --rename --package ${old_diverter} \
			--divert "$2" "$1"
}

if [ "$1" = "configure" ] && [ "$2" = "" ]
then

        # <target: squeeze>
	# remove obsolete diversions from nvidia-glx-legacy{,-71xx}-dev
	undivert /usr/lib/libGL.a	/usr/lib/nvidia/libGL.a.xlibmesa
	undivert /usr/X11R6/lib/libGL.a	/usr/X11R6/lib/nvidia/libGL.a.xlibmesa

	rmdir /usr/lib/nvidia /usr/X11R6/lib/nvidia /usr/X11R6/lib /usr/X11R6 2>/dev/null || true
        # </target: squeeze>

fi


#DEBHELPER#

exit 0
