#! /bin/sh
set -e

if [ "$1" = "configure" ] && [ "$2" = "" ]
then

        # <target: squeeze>
        # remove obsolete diversions from nvidia-glx-legacy-71xx-dev
	dpkg-divert --remove --rename --package nvidia-glx-legacy-71xx-dev --divert /usr/lib/nvidia/libGL.a.xlibmesa  /usr/lib/libGL.a > /dev/null
	dpkg-divert --remove --rename --package nvidia-glx-legacy-71xx-dev --divert /usr/X11R6/lib/nvidia/libGL.a.xlibmesa /usr/X11R6/lib/libGL.a > /dev/null

	rmdir /usr/lib/nvidia /usr/X11R6/lib/nvidia /usr/X11R6/lib /usr/X11R6 2>/dev/null || true
        # </target: squeeze>

fi


#DEBHELPER#

exit 0
