#!/bin/sh
set -e


#DIVERT_QUIET="--quiet"

# <target: squeeze>
dpkg-maintscript-helper rm_conffile /etc/default/nvidia-glx 96.43.17~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/nvidia-glx 96.43.17~ -- "$@"
# </target: squeeze>


case "$1" in
    install|upgrade)

	# the destination directory for the diversions
	test -d /usr/lib/nvidia || \
		mkdir -p /usr/lib/nvidia || true

	# make new diversions
	dpkg-divert $DIVERT_QUIET --add --rename --package $DPKG_MAINTSCRIPT_PACKAGE --divert \
		/usr/lib/nvidia/libglx.so.xlibmesa \
		/usr/lib/xorg/modules/extensions/libglx.so

    ;;
esac


#DEBHELPER#

exit 0
