#!/bin/sh
set -e


# <target: squeeze>
dpkg-maintscript-helper rm_conffile /etc/default/nvidia-glx-legacy 71.86.13-2~ nvidia-glx-legacy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/nvidia-glx-legacy 71.86.13-2~ nvidia-glx-legacy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/$DPKG_MAINTSCRIPT_PACKAGE 71.86.13-2~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/$DPKG_MAINTSCRIPT_PACKAGE 71.86.13-2~ -- "$@"
# </target: squeeze>


# $1=original $2=diverted
undivert()
{
	old_diverter="$(dpkg-divert --listpackage "$1")"
	test -z "$old_diverter" || \
		dpkg-divert --remove --rename --package ${old_diverter} \
			--divert "$2" "$1"
}

case "$1" in
    configure)

	# <target: squeeze>
	# also do this on new installations, we might take over nvidia-glx-legacy
	if dpkg --compare-versions "$2" lt 71.86.13-2 ; then
	    update-rc.d nvidia-glx-legacy remove || true
	    update-rc.d $DPKG_MAINTSCRIPT_PACKAGE remove || true
	fi
	# </target: squeeze>

	# <target: squeeze>
        if dpkg --compare-versions "$2" lt-nl 71.86.13-2 ; then
	    if [ -f /etc/default/$DPKG_MAINTSCRIPT_PACKAGE.dpkg-new ]; then
		rm -f /etc/default/$DPKG_MAINTSCRIPT_PACKAGE.dpkg-new
	    fi
	fi
	# </target: squeeze>

        # <target: squeeze>
	# also do this on new installations, we might take over nvidia-glx-legacy
	if dpkg --compare-versions "$2" lt 71.86.13-2 ; then
		# remove obsolete diversions
		undivert /usr/lib/xorg/modules/extensions/libGLcore.so	/usr/lib/nvidia/libGLcore.so.xlibmesa
		undivert /usr/lib/xorg/modules/extensions/libGLcore.a	/usr/lib/nvidia/libGLcore.a.xlibmesa
		undivert /usr/lib/xorg/modules/extensions/libglx.a	/usr/lib/nvidia/libglx.a.xlibmesa

		# remove obsolete diversions from nvidia-glx-legacy{,-71xx}-dev
		undivert /usr/lib/libGL.a				/usr/lib/nvidia/libGL.a.xlibmesa
		undivert /usr/X11R6/lib/libGL.a				/usr/X11R6/lib/nvidia/libGL.a.xlibmesa

		rmdir /usr/lib/nvidia /usr/X11R6/lib/nvidia /usr/X11R6/lib /usr/X11R6 2>/dev/null || true
        fi
        # </target: squeeze>

        # <target: squeeze>
	# remove libGL.so created before the trigger was moved to nvidia-libgl1
	# will be recreated by the trigger
	if dpkg --compare-versions "$2" lt-nl 71.86.13-2 ; then
		rm -f /usr/lib/libGL.so
	fi

	# activate the trigger
	dpkg-trigger /usr/lib/libGL.so
        # </target: squeeze>

    ;;
esac


#DEBHELPER#

exit 0
