#!/bin/sh
set -e


# <target: squeeze>
dpkg-maintscript-helper rm_conffile /etc/default/nvidia-glx-legacy 71.86.14~ nvidia-glx-legacy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/nvidia-glx-legacy 71.86.14~ nvidia-glx-legacy -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/$DPKG_MAINTSCRIPT_PACKAGE 71.86.14~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/$DPKG_MAINTSCRIPT_PACKAGE 71.86.14~ -- "$@"
# </target: squeeze>


#DEBHELPER#

exit 0
