#!/bin/sh
set -e


# $1=original $2=diverted
undivert()
{
	old_diverter="$(dpkg-divert --listpackage "$1")"
	test -z "$old_diverter" || \
		dpkg-divert --remove --rename --package ${old_diverter} \
			--divert "$2" "$1"
}

case "$1" in
    configure)

	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
	then
		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
		exit 1
	fi

	# <target: squeeze>
	# remove diversion created before the
	# /emul/ia32-linux/usr/lib => /usr/lib32 transition
	undivert /emul/ia32-linux/usr/lib/libGL.so.1.2	/emul/ia32-linux/usr/lib/nvidia/libGL.so.1.2.ia32-libs
	undivert /emul/ia32-linux/usr/lib/libGL.so.1	/emul/ia32-linux/usr/lib/nvidia/libGL.so.1.ia32-libs
	undivert /emul/ia32-linux/usr/lib/libGL.so	/emul/ia32-linux/usr/lib/nvidia/libGL.so.ia32-libs

	if [ -d /emul/ia32-linux/usr/lib/nvidia ]
	then
		rmdir /emul/ia32-linux/usr/lib/nvidia || true;
		rmdir /emul/ia32-linux/usr/lib /emul/ia32-linux/usr /emul/ia32-linux /emul 2>/dev/null || true
	fi
	# </target: squeeze>

	# <target: squeeze>
	# remove ancient diversions
	undivert /emul/ia32-linux/usr/X11R6/lib/libGL.so.1.2	 /emul/ia32-linux/usr/X11R6/lib/nvidia/libGL.so.1.2.ia32-libs
	undivert /emul/ia32-linux/usr/lib/X11R6/libGL.so.1	 /emul/ia32-linux/usr/lib/X11R6/nvidia/libGL.so.1.ia32-libs
	undivert /emul/ia32-linux/usr/lib/X11R6/libGL.so	 /emul/ia32-linux/usr/lib/X11R6/nvidia/libGL.so.ia32-libs

	rmdir /emul/ia32-linux/usr/lib/X11R6/nvidia /emul/ia32-linux/usr/lib/X11R6 2>/dev/null || true
	rmdir /emul/ia32-linux/usr/X11R6/lib/nvidia /emul/ia32-linux/usr/X11R6/lib /emul/ia32-linux/usr/X11R6 2>/dev/null || true
	rmdir /emul/ia32-linux/usr/lib /emul/ia32-linux/usr /emul/ia32-linux /emul 2>/dev/null || true
	# </target: squeeze>

    ;;
esac


#DEBHELPER#

exit 0
